// Company Information
export const COMPANY = {
  name: "The Last Clicks",
  email: "info@thelastclicks.com",
  mobile: "+91-8770155842",
  tagline: "Capturing Moments, Creating Memories",
  logo: "/images/logo-dark.png",
} as const;

// Navigation Links
export const NAV_LINKS = [
  { name: "Services", href: "/services" },
  { name: "Portfolio", href: "/portfolio" },
  { name: "About", href: "/about" },
  { name: "Contact", href: "/contact" },
] as const;

// Services
export const SERVICES = {
  photography: {
    name: "Photography",
    href: "/services/photography",
    description: "Professional photography services for all occasions",
    categories: [
      { name: "Wedding Photography", slug: "wedding", icon: "GiDiamondRing" },
      { name: "Portrait Photography", slug: "portrait", icon: "BsPersonBoundingBox" },
      { name: "Event Photography", slug: "event", icon: "MdCelebration" },
      { name: "Product Photography", slug: "product", icon: "BsBox" },
      { name: "Fashion Photography", slug: "fashion", icon: "GiLargeDress" },
      { name: "Corporate Photography", slug: "corporate", icon: "BsBuilding" },
    ],
  },
  videography: {
    name: "Videography",
    href: "/services/videography",
    description: "Cinematic video production for memorable stories",
    categories: [
      { name: "Wedding Films", slug: "wedding-films", icon: "BiCameraMovie" },
      { name: "Corporate Videos", slug: "corporate-videos", icon: "BsCameraVideo" },
      { name: "Music Videos", slug: "music-videos", icon: "BsMusicNoteBeamed" },
      { name: "Documentary", slug: "documentary", icon: "MdOutlineMovie" },
      { name: "Commercial Ads", slug: "commercial", icon: "BsTv" },
      { name: "Event Coverage", slug: "event-coverage", icon: "MdOutlineTheaters" },
    ],
  },
  editing: {
    name: "Editing Service",
    href: "/services/editing",
    description: "Transform your raw footage into stunning masterpieces",
    categories: [
      { name: "Photo Retouching", slug: "photo-retouching", icon: "HiSparkles" },
      { name: "Video Editing", slug: "video-editing", icon: "BsFilm" },
      { name: "Color Grading", slug: "color-grading", icon: "IoColorPaletteOutline" },
      { name: "Motion Graphics", slug: "motion-graphics", icon: "TbSparkles" },
      { name: "Audio Mixing", slug: "audio-mixing", icon: "BsHeadphones" },
      { name: "VFX & Animation", slug: "vfx-animation", icon: "HiOutlineStar" },
    ],
  },
} as const;

// Editors Data
export const EDITORS = [
  {
    id: 1,
    name: "Rahul Sharma",
    role: "Senior Video Editor",
    specialization: ["Video Editing", "Color Grading", "Motion Graphics"],
    experience: "8+ Years",
    projects: 500,
    image: "/images/editors/editor-1.jpg",
    bio: "Award-winning video editor with expertise in cinematic storytelling and color grading.",
  },
  {
    id: 2,
    name: "Priya Patel",
    role: "Photo Retouching Expert",
    specialization: ["Photo Retouching", "Portrait Enhancement", "Beauty Editing"],
    experience: "6+ Years",
    projects: 1200,
    image: "/images/editors/editor-2.jpg",
    bio: "Specialized in high-end photo retouching for fashion and portrait photography.",
  },
  {
    id: 3,
    name: "Amit Kumar",
    role: "Motion Graphics Designer",
    specialization: ["Motion Graphics", "VFX", "Animation"],
    experience: "5+ Years",
    projects: 300,
    image: "/images/editors/editor-3.jpg",
    bio: "Creative motion designer bringing ideas to life through stunning animations.",
  },
  {
    id: 4,
    name: "Sneha Reddy",
    role: "Color Grading Specialist",
    specialization: ["Color Grading", "Film Look", "Cinematic Tones"],
    experience: "7+ Years",
    projects: 400,
    image: "/images/editors/editor-4.jpg",
    bio: "Expert colorist known for creating signature looks for films and commercials.",
  },
  {
    id: 5,
    name: "Vikram Singh",
    role: "Audio Engineer",
    specialization: ["Audio Mixing", "Sound Design", "Music Production"],
    experience: "10+ Years",
    projects: 600,
    image: "/images/editors/editor-5.jpg",
    bio: "Professional audio engineer with background in music and film sound design.",
  },
  {
    id: 6,
    name: "Anjali Verma",
    role: "VFX Artist",
    specialization: ["VFX", "Compositing", "3D Integration"],
    experience: "4+ Years",
    projects: 200,
    image: "/images/editors/editor-6.jpg",
    bio: "Skilled VFX artist creating seamless visual effects for diverse projects.",
  },
] as const;

// Editing Service Features
export const EDITING_FEATURES = [
  {
    title: "Fast Turnaround",
    description: "Get your edited content delivered within 24-72 hours",
    icon: "BsLightning",
  },
  {
    title: "Unlimited Revisions",
    description: "We work until you're 100% satisfied with the result",
    icon: "BiRefresh",
  },
  {
    title: "Premium Quality",
    description: "4K & 8K support with professional-grade output",
    icon: "IoDiamondOutline",
  },
  {
    title: "Secure Transfer",
    description: "Your files are encrypted and handled with care",
    icon: "BiLock",
  },
] as const;

// Pricing Tiers
export const EDITING_PRICING = [
  {
    name: "Basic",
    price: "₹999",
    period: "per project",
    features: [
      "Basic color correction",
      "Simple cuts & transitions",
      "Background music",
      "1 revision round",
      "720p delivery",
    ],
    popular: false,
  },
  {
    name: "Professional",
    price: "₹2,999",
    period: "per project",
    features: [
      "Advanced color grading",
      "Smooth transitions & effects",
      "Custom music & sound design",
      "3 revision rounds",
      "4K delivery",
      "Motion graphics",
    ],
    popular: true,
  },
  {
    name: "Premium",
    price: "₹7,999",
    period: "per project",
    features: [
      "Cinematic color grading",
      "Premium VFX & animations",
      "Professional sound mixing",
      "Unlimited revisions",
      "4K/8K delivery",
      "Priority support",
      "Raw files included",
    ],
    popular: false,
  },
] as const;

// Portfolio Data
export const PHOTOGRAPHY_PORTFOLIO = [
  {
    id: "photo-1",
    title: "Royal Wedding in Udaipur",
    category: "Wedding",
    location: "Udaipur, Rajasthan",
    date: "December 2025",
    description: "A magnificent three-day celebration capturing love, tradition, and royal elegance at the Lake Palace.",
    thumbnail: "/images/portfolio/wedding-1.jpg",
    images: [
      "/images/portfolio/wedding-1-1.jpg",
      "/images/portfolio/wedding-1-2.jpg",
      "/images/portfolio/wedding-1-3.jpg",
      "/images/portfolio/wedding-1-4.jpg",
    ],
    featured: true,
  },
  {
    id: "photo-2",
    title: "Fashion Editorial - Vogue India",
    category: "Fashion",
    location: "Mumbai, Maharashtra",
    date: "November 2025",
    description: "High-fashion editorial shoot featuring contemporary Indian designers for Vogue India's winter collection.",
    thumbnail: "/images/portfolio/fashion-1.jpg",
    images: [
      "/images/portfolio/fashion-1-1.jpg",
      "/images/portfolio/fashion-1-2.jpg",
      "/images/portfolio/fashion-1-3.jpg",
    ],
    featured: true,
  },
  {
    id: "photo-3",
    title: "Corporate Headshots - Tech Mahindra",
    category: "Corporate",
    location: "Pune, Maharashtra",
    date: "October 2025",
    description: "Professional corporate portraits for Tech Mahindra's executive leadership team.",
    thumbnail: "/images/portfolio/corporate-1.jpg",
    images: [
      "/images/portfolio/corporate-1-1.jpg",
      "/images/portfolio/corporate-1-2.jpg",
    ],
    featured: false,
  },
  {
    id: "photo-4",
    title: "Product Photography - Tanishq",
    category: "Product",
    location: "Studio, Bhopal",
    date: "September 2025",
    description: "Luxury jewelry photography showcasing Tanishq's new bridal collection with intricate details.",
    thumbnail: "/images/portfolio/product-1.jpg",
    images: [
      "/images/portfolio/product-1-1.jpg",
      "/images/portfolio/product-1-2.jpg",
      "/images/portfolio/product-1-3.jpg",
    ],
    featured: true,
  },
  {
    id: "photo-5",
    title: "Destination Wedding - Goa",
    category: "Wedding",
    location: "Goa",
    date: "January 2025",
    description: "Beach wedding capturing sunset ceremonies, cocktail parties, and intimate moments by the sea.",
    thumbnail: "/images/portfolio/wedding-2.jpg",
    images: [
      "/images/portfolio/wedding-2-1.jpg",
      "/images/portfolio/wedding-2-2.jpg",
      "/images/portfolio/wedding-2-3.jpg",
    ],
    featured: false,
  },
  {
    id: "photo-6",
    title: "Portrait Series - Artists of Bhopal",
    category: "Portrait",
    location: "Bhopal, MP",
    date: "August 2025",
    description: "An intimate portrait series documenting the lives and workspaces of local artists.",
    thumbnail: "/images/portfolio/portrait-1.jpg",
    images: [
      "/images/portfolio/portrait-1-1.jpg",
      "/images/portfolio/portrait-1-2.jpg",
    ],
    featured: false,
  },
  {
    id: "photo-7",
    title: "Annual Gala - Infosys Foundation",
    category: "Event",
    location: "Bengaluru, Karnataka",
    date: "July 2025",
    description: "Coverage of Infosys Foundation's annual charity gala featuring celebrities and philanthropists.",
    thumbnail: "/images/portfolio/event-1.jpg",
    images: [
      "/images/portfolio/event-1-1.jpg",
      "/images/portfolio/event-1-2.jpg",
      "/images/portfolio/event-1-3.jpg",
    ],
    featured: true,
  },
  {
    id: "photo-8",
    title: "E-commerce Catalog - Myntra",
    category: "Product",
    location: "Studio, Mumbai",
    date: "June 2025",
    description: "High-volume e-commerce product photography for Myntra's summer fashion collection.",
    thumbnail: "/images/portfolio/product-2.jpg",
    images: [
      "/images/portfolio/product-2-1.jpg",
      "/images/portfolio/product-2-2.jpg",
    ],
    featured: false,
  },
] as const;

export const VIDEOGRAPHY_PORTFOLIO = [
  {
    id: "video-1",
    title: "Wedding Film - Priya & Arjun",
    category: "Wedding Film",
    location: "Jaipur, Rajasthan",
    date: "December 2025",
    duration: "12:45",
    description: "A cinematic wedding film capturing the essence of a traditional Rajasthani celebration with modern storytelling.",
    thumbnail: "/images/portfolio/video-wedding-1.jpg",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoType: "youtube",
    featured: true,
  },
  {
    id: "video-2",
    title: "Brand Film - Tata Motors",
    category: "Corporate",
    location: "Multiple Locations",
    date: "November 2025",
    duration: "03:30",
    description: "Corporate brand film showcasing Tata Motors' commitment to innovation and sustainability.",
    thumbnail: "/images/portfolio/video-corporate-1.jpg",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoType: "youtube",
    featured: true,
  },
  {
    id: "video-3",
    title: "Music Video - Rising Stars",
    category: "Music Video",
    location: "Mumbai, Maharashtra",
    date: "October 2025",
    duration: "04:15",
    description: "High-energy music video production for indie band featuring dynamic visuals and creative storytelling.",
    thumbnail: "/images/portfolio/video-music-1.jpg",
    videoUrl: "/videos/portfolio/music-video-1.mp4",
    videoType: "direct",
    featured: true,
  },
  {
    id: "video-4",
    title: "Documentary - Crafts of Madhya Pradesh",
    category: "Documentary",
    location: "Madhya Pradesh",
    date: "September 2025",
    duration: "28:00",
    description: "A documentary exploring the rich heritage of traditional crafts and artisans of Madhya Pradesh.",
    thumbnail: "/images/portfolio/video-documentary-1.jpg",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoType: "youtube",
    featured: false,
  },
  {
    id: "video-5",
    title: "Commercial - Coca-Cola Diwali",
    category: "Commercial",
    location: "Delhi NCR",
    date: "October 2025",
    duration: "00:45",
    description: "Festive commercial celebrating Diwali traditions with Coca-Cola's 'Share Happiness' campaign.",
    thumbnail: "/images/portfolio/video-commercial-1.jpg",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoType: "youtube",
    featured: true,
  },
  {
    id: "video-6",
    title: "Event Highlight - TEDx Bhopal",
    category: "Event Coverage",
    location: "Bhopal, MP",
    date: "August 2025",
    duration: "06:30",
    description: "Highlight reel capturing the inspiring talks and moments from TEDx Bhopal 2025.",
    thumbnail: "/images/portfolio/video-event-1.jpg",
    videoUrl: "/videos/portfolio/tedx-bhopal.mp4",
    videoType: "direct",
    featured: false,
  },
  {
    id: "video-7",
    title: "Wedding Teaser - Meera & Vikram",
    category: "Wedding Film",
    location: "Kerala",
    date: "July 2025",
    duration: "02:30",
    description: "A dreamy wedding teaser set against the backwaters of Kerala with drone cinematography.",
    thumbnail: "/images/portfolio/video-wedding-2.jpg",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoType: "youtube",
    featured: false,
  },
  {
    id: "video-8",
    title: "Product Launch - OnePlus India",
    category: "Commercial",
    location: "Mumbai, Maharashtra",
    date: "June 2025",
    duration: "01:30",
    description: "Dynamic product launch video featuring the latest OnePlus smartphone with cutting-edge visuals.",
    thumbnail: "/images/portfolio/video-commercial-2.jpg",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoType: "youtube",
    featured: false,
  },
] as const;

export const PORTFOLIO_CATEGORIES = {
  photography: ["All", "Wedding", "Fashion", "Corporate", "Product", "Portrait", "Event"],
  videography: ["All", "Wedding Film", "Corporate", "Music Video", "Documentary", "Commercial", "Event Coverage"],
} as const;
