<?php

namespace App\Mail;

use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Address;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Mail\Mailables\Headers;

class OutreachMail extends Mailable
{
    /**
     * @param  array<string, string>  $contact  Merge fields from the outreach queue.
     * @param  string  $step  One of config('outreach.steps').
     * @param  string  $messageId  Pre-generated, without angle brackets. Generated by the
     *                             caller rather than read back off the sent message so the
     *                             follow-ups have something stable to thread against --
     *                             SMTP gives us no reliable way to read the final id back.
     * @param  string|null  $inReplyTo  The first-touch message id, for follow-ups.
     */
    public function __construct(
        public array $contact,
        public string $step,
        public string $subjectLine,
        public string $messageId,
        public ?string $inReplyTo = null,
    ) {}

    public function envelope(): Envelope
    {
        return new Envelope(
            from: new Address(
                config('mail.from.address'),
                config('outreach.from_name'),
            ),
            replyTo: [new Address(config('outreach.reply_to'))],
            subject: $this->subjectLine,
        );
    }

    public function headers(): Headers
    {
        $unsubscribe = config('outreach.reply_to');

        $text = [
            // Gmail only *requires* this above 5k/day, but the opt-out button it
            // puts in the header is the cheap alternative to a spam complaint --
            // and at 62 recipients a single complaint is 1.6%, five times over
            // Google's 0.30% threshold.
            'List-Unsubscribe' => '<mailto:'.$unsubscribe.'?subject=unsubscribe>',
            'List-Unsubscribe-Post' => 'List-Unsubscribe=One-Click',
        ];

        // Threading the follow-ups onto the original turns them into a reply in
        // the recipient's client instead of a second cold email. References must
        // carry the whole chain, not just the immediate parent.
        if ($this->inReplyTo !== null) {
            $text['In-Reply-To'] = '<'.$this->inReplyTo.'>';
            $text['References'] = '<'.$this->inReplyTo.'>';
        }

        return new Headers(
            messageId: $this->messageId,
            text: $text,
        );
    }

    public function content(): Content
    {
        return new Content(
            text: 'emails.outreach.'.$this->step,
            with: [
                'c' => array_map($this->plain(...), $this->contact),
                'fromName' => config('outreach.from_name'),
                'phone' => config('outreach.signature_phone'),
                'site' => config('outreach.signature_site'),
                'instagram' => config('outreach.signature_instagram'),
                'unsubscribe' => config('outreach.reply_to'),
            ],
        );
    }

    /**
     * Flatten a merge value to something safe to drop into a text/plain body.
     *
     * The views print with {!! !!} on purpose: Blade's escaping is for HTML, and
     * in a plain-text mail it corrupts real data -- an organizer called
     * "Smith & Sons" arrives as "Smith &amp; Sons". There is no injection to
     * guard against in text/plain, so the escaping is pure downside.
     */
    private function plain(mixed $value): string
    {
        return trim(html_entity_decode(strip_tags((string) $value), ENT_QUOTES | ENT_HTML5, 'UTF-8'));
    }
}
